name: Trogdord Tests
on: [push, pull_request]

jobs:

   test_trogdord:

      runs-on: ubuntu-latest
      name: Trogdord

      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Build and run
           uses: ./.github/workflows/actions/test_trogdord
