name: Trogdord Tests
on: [push, pull_request]

jobs:

   test_trogdord:

      runs-on: ubuntu-latest
      name: Trogdord Tests

      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Build and run
           uses: ./.github/workflows/actions/test_trogdord
         - uses: actions/upload-artifact@v2
           if: failure()
           with:
             name: coredump
             path: /usr/share/apport/apport